ilm/urls.py
from django.urls import path, include
from . import views

app_name = 'ilm'
urlpatterns = [
    path('', views.index, name='index'),
    # path('mobile/', views.index_mobile, name='index_mobile'),
    path('history/', views.history, name='history'),
    path('forecasts/', views.forecasts, name='forecasts'),
    path('forecasts/<str:asukoht>/', views.forecasts, name='forecasts_with_asukoht'),
    # path('forecasts_yrno/', views.forecasts_yrno, name='forecasts_yrno'),
    path('forecasts_quality/', views.forecasts_quality, name='forecasts_quality'),
    path('maxmin/', views.maxmin, name='maxmin'),
    path('mixed_ilmateade/', views.mixed_ilmateade, name='mixed_ilmateade'),
    path('container_history_andmed/', views.container_history_andmed, name='container_history_andmed'),
    path('container_history_aasta/', views.container_history_aasta, name='container_history_aasta'),
    path('container_history_kuud/', views.container_history_kuud, name='container_history_kuud'),
    path('container_history_kuu/', views.container_history_kuu, name='container_history_kuu'),
    path('container_history_kuud_aastatekaupa/', views.container_history_kuud_aastatekaupa, name='container_history_kuud_aastatekaupa'),
    path('container_history_p2ev/', views.container_history_p2ev, name='container_history_p2ev'),
    path('container_history_p2evad/', views.container_history_p2evad, name='container_history_p2evad'),
    path('container_history_aastad/', views.container_history_aastad, name='container_history_aastad'),
    # path('pyimage/', PyImageView.as_view(), name='pyimage_view'),
]

kroonika/urls.py
# kroonika URL Configuration

from ajax_select import urls as ajax_select_urls

# from django.contrib.auth import views as auth_views
from django.conf import settings
# from django.conf.urls import handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

from .sitemaps import StaticViewSitemap, ArtikkelSitemap, IsikSitemap, OrganisatsioonSitemap, ObjektSitemap
from .routers import router
from wiki import views, specials

# sitemaps.xml
sitemaps = {
    'static': StaticViewSitemap,
    'lood': ArtikkelSitemap,
    'isikud': IsikSitemap,
    'asutised': OrganisatsioonSitemap,
    'kohad': ObjektSitemap
}

# schema_url_patterns = [
#     path('api/', include(router.urls)),
# ]

# API
schema_view = get_schema_view(
    title='Valga linna kroonika API',
    # url='https://valgalinn/api/',
    # patterns=schema_url_patterns
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.algus, name='algus'),
    path('info/', views.info, name='info'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')), # django-allauth
    path('ajax_select/', include(ajax_select_urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	path('api/', include(router.urls)),
    path('blog/', include('blog.urls'), name='blog'),
    path('kiri/', include('kiri.urls'), name='kiri'),
    path('ilm/', include('ilm.urls'), name='ilm'),
    path('inlineedit/', include('inlineedit.urls'), name='save'), # https://github.com/ptav/django-inlineedit
    path('docs/', include_docs_urls(title='Valga linna kroonika API')),
    path('markdownx/', include('markdownx.urls')),
    path('privacy/', views.privacy, name='privacy'),
    path('schema/', schema_view),
    path('wiki/', include('wiki.urls')),
    path('kaart/', views.kaart, name='kaart'),
    path('kaart/get_big_leaflet_map/', views.get_big_leaflet_map, name='get_big_leaflet_map'),
    path('kaart/<int:aasta>/', views.kaart, name='kaart'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('valga438/', specials.special_valga438, name='special_valga438'),
    # path('valga439/', specials.special_valga439, name='special_valga439'),
    # path('valga440/', specials.special_valga440, name='special_valga440'),
    # path('valga441/', specials.special_valga441, name='special_valga441'),
    # path('j6ul2020/', specials.special_j6ul2020, name='special_j6ul2020'),
    # path('j6ul2021/', specials.special_j6ul2021, name='special_j6ul2021'),
    # path('j6ul2022/', specials.special_j6ul2022, name='special_j6ul2022'),
    # path('j6ul2023/', specials.special_j6ul2023, name='special_j6ul2023'),
    # path('j6ul2024/', specials.special_j6ul2024, name='special_j6ul2024'),
    path('j6ul2025/', specials.special_j6ul2025, name='special_j6ul2025'),
    path('vgvk/', include('vgvk.urls')),
    path('raise_500_error/', views.raise_500_error, name='raise_500_error'), # http500 veateate testimiseks
    # path("__debug__/", include("debug_toolbar.urls")), # https://django-debug-toolbar.readthedocs.io
]

#error handling
handler500 = 'wiki.views.custom_500'

# Haldusliidese pealkirjad
admin.site.site_header = 'valgalinn.ee sisuhaldus'
admin.site.site_title = 'valgalinn.ee sisuhaldus'

# Serve static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve user uploaded media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilm/forms.py
from datetime import datetime
import calendar

from django import forms

class NameForm(forms.Form):
    aasta = forms.IntegerField(label='Aasta')
    kuu = forms.IntegerField(label='Kuu', required=False)
    p2ev = forms.IntegerField(label='Päev',required=False)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['aasta'].widget.attrs.update(
            { 'class': 'w3-border-0',
             'placeholder': 'Aasta...',
             'min': 1900,
             'max': datetime.now().year
             }
        )
        self.fields['kuu'].widget.attrs.update(
            {'class': 'w3-border-0',
             'placeholder': 'Kuu...',
             'min': 0,
             'max': 12
             }
        )
        self.fields['p2ev'].widget.attrs.update(
            {'class': 'w3-border-0',
             'placeholder': 'Päev...',
             'maxlength': '2',
             'min': 0,
             'max': 31
             }
        )
        
    def clean(self):
        cleaned_data = super().clean()
        aasta = cleaned_data.get("aasta")
        p2ev = cleaned_data.get("p2ev")
        if p2ev:
            if (p2ev < 1) or (p2ev > 31):
                msg = "Päev peab olema vahemikus 1-31 või tühi"
                self.add_error('p2ev', msg)
        kuu = cleaned_data.get("kuu")
        if kuu:
            if kuu < 1 or kuu > 12:
                msg = "Kuu peab olema vahemikus 1-12 või tühi"
                self.add_error('kuu', msg)
            else:
                if aasta and kuu and p2ev:
                    c = calendar.Calendar()
                    if (aasta, kuu, p2ev) not in c.itermonthdays3(aasta, kuu):
                        raise forms.ValidationError(
                            "Sellist kuupäeva ei saa olla"
                        )

ilm/views.py
import calendar
from datetime import datetime, timedelta
import json

import logging
from sqlite3 import Row
logger = logging.getLogger(__name__)

import os
from pathlib import Path
import tempfile

import django
from django.conf import settings
import pandas as pd
import pytz
import redis
# import requests

if __name__ == "__main__":
    # from django.test.utils import setup_test_environment
    os.environ['DJANGO_SETTINGS_MODULE'] = 'kroonika.settings'
    django.setup()
    # setup_test_environment()

from django.contrib.auth.models import AnonymousUser
from django.db import connection
from django.db.models import F, RowRange, Window, Count, Sum, Avg, Min, Max

from django.http import JsonResponse
from django.shortcuts import render

from ilm.forms import NameForm
from ilm.models import Ilm
from ilm.utils import utils, IlmateenistusValga
import ilm.utils.ephem_util as ephem_data

if settings.REDIS_INUSE:
    redis_client = redis.Redis(host=settings.REDIS_HOST, port=6379, db=0)

bdi = IlmateenistusValga.IlmateenistusData()

KUUD = [
    '', # Tühi selleks et kuunumber=indeks
    'jaanuar',
    'veebruar',
    'märts',
    'aprill',
    'mai',
    'juuni',
    'juuli',
    'august',
    'september',
    'oktoober',
    'november',
    'detsember'
]
TMP_ALGUSKUVA = Path(tempfile.gettempdir()) / '_valgalinn.ee_ilm.tmp'

# Highcharts vaikevärvid
COLORS = [
    "#7cb5ec", # helesinine
    "#434348", # tumehall
    "#90ed7d", # heleroheline
    "#f7a35c", # oranzh
    "#8085e9", # lillakas sinine
    "#f15c80", # tumeroosa
    "#e4d354", # murtud roheline
    "#2b908f", # sinakas roheline
    "#f45b5b", # kahvatu punane
    "#91e8e1" # murtud heleroheline
]

# Temperatuuride värvid
COLORS_TEMP = {
    'negative': '#48AFE8', # helesinine
    'positive': '#FF3333'  # helepunane
}

# OpenWeatherMaps ilmakoodid
OWM_CODES = {
    "200": "nõrk äikesevihm", # thunderstorm with light rain;Thunderstorm
    "201": "äikesevihm", # thunderstorm with rain;Thunderstorm
    "202": "tugev äikesevihm", # thunderstorm with heavy rain;Thunderstorm
    "210": "nõrk äike", # light thunderstorm;Thunderstorm
    "211": "äike", # thunderstorm;Thunderstorm
    "212": "tugev äike", # heavy thunderstorm;Thunderstorm
    "221": "äge äike", # ragged thunderstorm;Thunderstorm
    "230": "nõrk äikesevihm", # thunderstorm with light drizzle;Thunderstorm
    "231": "äikesevihm", # thunderstorm with drizzle;Thunderstorm
    "232": "tugev äikesevihm", # thunderstorm with heavy drizzle;Thunderstorm
    "300": "nõrk uduvihm", # light intensity drizzle;Drizzle
    "301": "uduvihm", # drizzle;Drizzle
    "302": "tugev uduvihm", # heavy intensity drizzle;Drizzle
    "310": "kerge uduvihm", # light intensity drizzle rain;Drizzle
    "311": "uduvihm", # drizzle rain;Drizzle
    "312": "tugev uduvihm", # heavy intensity drizzle rain;Drizzle
    "313": "tugev uduvihm", # shower rain and drizzle;Drizzle
    "314": "tugev uduvihm", # heavy shower rain and drizzle;Drizzle
    "321": "tugev uduvihm", # shower drizzle;Drizzle
    "500": "nõrk vihm", # light rain;Rain
    "501": "vihm", # moderate rain;Rain
    "502": "tugev vihm", # heavy intensity rain;Rain
    "503": "väga tugev vihm", # very heavy rain;Rain
    "504": "ekstreemne vihmasadu", # extreme rain;Rain
    "511": "külmuv vihm", # freezing rain;Rain
    "520": "nõrk paduvihm", # light intensity shower rain;Rain
    "521": "paduvihm", # shower rain;Rain
    "522": "tugev paduvihm", # heavy intensity shower rain;Rain
    "531": "väga tugev paduvihm", # ragged shower rain;Rain
    "600": "kerge lumesadu", # light snow;Snow
    "601": "lumesadu", # Snow;Snow
    "602": "tugev lumesadu", # Heavy snow;Snow
    "611": "lörts", # Sleet;Snow
    "612": "kerge lörtsisadu", # Light shower sleet;Snow
    "613": "tugev lörtsisadu", # Shower sleet;Snow
    "615": "kerge lörtsisadu", # Light rain and snow;Snow
    "616": "lörts", # Rain and snow;Snow
    "620": "kerge lumesadu", # Light shower snow;Snow
    "621": "lumesadu", # Shower snow;Snow
    "622": "tugev lumesadu", # Heavy shower snow;Snow
    "701": "uduvine", # mist;Mist
    "711": "suits", # Smoke;Smoke
    "721": "vine", # Haze;Haze
    "731": "liiva-/tolmupöörised", # sand/ dust whirls;Dust
    "741": "udu", # fog;Fog
    "751": "liiv", # sand;Sand
    "761": "tolm", # dust;Dust
    "762": "vulkaaniline tuhk", # volcanic ash;Ash
    "771": "tuulepuhangud", # squalls;Squall
    "781": "tornaado", # tornado;Tornado
    "800": "selge", # clear sky;Clear
    "801": "õrn pilvisus", # few clouds: 11-25%;Clouds
    "802": "vahelduv pilvisus", # scattered clouds: 25-50%;Clouds
    "803": "vahelduv pilvisus", # broken clouds: 51-84%;Clouds
    "804": "pilvine", # overcast clouds: 85-100%;Clouds
}

# Decimal andmeväljade teisendamiseks, mis võivad olla tühjad <NULL>
def float_or_none(value):
    try:
        return float(value)
    except:
        return None

def float_or_zero(value):
    try:
        return float(value)
    except:
        return 0

def index(request):
    # Avalehekülg, kus näidatakse 24h ilmaajalugu + 48h prognoos
    history = utils.get_ilmateenistus_history()
    sun = ephem_data.get_sun_data()
    current_weather = utils.get_ilmateenistus_now()
    forecasts = utils.get_forecasts(hours=12)

    context = {
        # 'weather': weather,
        'history': history,
        'sun': sun,
        'current_weather': current_weather,
        'forecasts': forecasts,
        # 'ilm_ilmateenistus_now': ilm_ilmateenistus_now,
        # 'ilm_ilmateenistus_forecast': ilm_ilmateenistus_forecast
    }
    return render(request, 'ilm/index.html', context)

def history(request):
    # Ajalooliste ilmaandmete töötlused
    # saab ka küsida kujul /ilm/history/?aasta=2019&kuu=1&p2ev=1
    params = request.GET # Kas on parameetrid, kui jah, siis kasutada neid v6i vaikimisi salvestatud
    aasta = params.get('aasta')
    if aasta:
        try:
            aasta = int(aasta)
        except:
            aasta = bdi.aasta
        kuu = params.get('kuu')
        if kuu:
            try:
                kuu = int(kuu)
            except:
                kuu = bdi.kuu
            p2ev = params.get('p2ev')
            try:
                p2ev = int(p2ev)
            except:
                p2ev = 1
        else:
            kuu = 1
            p2ev = 1
    try:
        testime_kuup2eva = datetime(int(aasta), int(kuu), int(p2ev)) # Kas küsitud kuupäev on loogiline
        bdi.aasta = aasta
        bdi.kuu = kuu
        bdi.p2ev = p2ev
        form = NameForm(initial={'aasta': aasta, 'kuu': kuu, 'p2ev': p2ev})
    except:
        form = NameForm(initial={'aasta': bdi.aasta, 'kuu': bdi.kuu, 'p2ev': bdi.p2ev})

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            bdi.aasta = form.cleaned_data['aasta']
            bdi.kuu = form.cleaned_data['kuu']
            bdi.p2ev = form.cleaned_data['p2ev']

    return render(
        request,
        'ilm/history.html',
        {
            'form': form
        }
    )


def container_history_andmed(request):
    andmed = {'parameetrid': bdi.bdi_startstopp()}
    return JsonResponse(andmed)


def container_history_aastad(request):
    # Täisaastate ilmaandmed graafikuna
    chart = dict()
    sel = list(bdi.qs_years)
    categories = []
    sel_temp_averages = []
    sel_temp_ranges = []
    sel_prec_sums = []
    for i in range(len(sel)):
        # X-telje väärtused
        categories.append(f"{sel[i]['timestamp__year']}")
        # Valitud kuu päeva andmed
        # print(i, sel[i])
        sel_temp_averages.append([i, round(float(sel[i]['airtemperature__avg']), 1)])
        sel_temp_ranges.append(
            [
                round(float(sel[i]['airtemperature__min']), 1),
                round(float(sel[i]['airtemperature__max']), 1)
            ]
        )
        if sel[i]['precipitations__sum']:
            sel_prec_sums.append(round(float(sel[i]['precipitations__sum']), 1))
        else:
            sel_prec_sums.append(0)  # Kui mõõtmistulemusi kogu päev polnud

    hist_temp_average = round(sum(data[1] for data in sel_temp_averages) / len(sel_temp_averages), 1)
    chart['aastad'] = f'{min(categories)}-{max(categories)}'
    # Graafiku andmeseeriate kirjeldamine
    series_sel_temp_averages = {
        'name': f'aasta keskmine',
        'regression': True,
        'regressionSettings': {
            'type': 'linear',
            'color': 'rgba(223, 83, 83, .9)'
        },
        'data': sel_temp_averages,
        'zIndex': 2,
        'marker': {
            'lineWidth': 2,
        },
        'color': '#FF3333',
        'negativeColor': '#48AFE8'
    }
    series_sel_temp_ranges = {
        'name': f'aasta min/max',
        'data': sel_temp_ranges,
        'type': 'arearange',
        'lineWidth': 0,
        'linkedTo': ':previous',
        'color': COLORS[0],
        'fillOpacity': 0.3,
        'zIndex': 0,
        'marker': {
            'enabled': False
        }
    }
    series_sel_prec_sums = {
        'name': f'aasta sademed',
        'type': 'column',
        'yAxis': 1,
        'data': sel_prec_sums,
        'color': COLORS[0],
        'tooltip': {
            'valueSuffix': ' mm'
        }
    }
    # Graafiku joonistamine
    chart = {
        'title': {
            'text': f'{chart["aastad"]} Valga linnas'
        },

        'subtitle': {
            'text': 'Allikas: <a href="https://www.ilmateenistus.ee/asukoha-prognoos/?id=8918" target="_blank">ilmateenistus.ee</a>',
            'floating': True,
            'align': 'left',
            'x': 30,
            'verticalAlign': 'bottom',
            'y': 25
        },

        'xAxis': {
            'categories': categories,
            # 'labels': {
            #     'format': '{value:%e. %b}'
            # }
        },

ilm/templates/ilm/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <meta charset="utf-8">
    <title>{% block title %}Valga linna ilm{% endblock %}</title>
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Custom CSS -->
  	<link rel="stylesheet" href="{% static 'wiki/css/kroonika_general.css' %}">
	{% block stylesheet %}{% endblock %}

		<link rel="shortcut icon" href="{% static 'ilm/img/favicon.ico' %}">
  </head>
  <body class="w3-light-grey">
    <header>
    </header>
	<!-- Navbar -->
	<div id="top" class="w3-top">
	  <div class="w3-bar w3-left-align w3-large w3-padding">
		<!-- <a class="w3-bar-item w3-button w3-hide-large w3-right w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="myFunction()"><i class="fa fa-bars"></i></a> -->
		<a
				href="{% url 'ilm:index' %}"
				class="w3-bar-item w3-button w3-theme-d4 w3-hover-white">
			<i class="fa w3-margin-right">
				<img
						src="{% static 'ilm/img/220px-Valga_coat_of_arms.svg.png' %}"
						style='max-height:22px;'
						alt="vapp"
				></i>
			Valga linna ilm
		</a>
		<a
				href="{% url 'ilm:history' %}"
				class="w3-bar-item w3-button w3-hide-small w3-hover-white"
				title="Ilmaandmete ajalugu">
			<i class="fa fa-line-chart"></i>
		</a>
		<a
				href="{% url 'algus' %}"
				class="w3-bar-item w3-button w3-hide-small w3-hover-white"
				title="Valga linna kroonika">
			<i class="fa fa-leanpub"></i>
		</a>
		<a href="https://et.wikipedia.org/wiki/Valga" target="blank" class="w3-bar-item w3-button w3-hide-medium  w3-hide-small w3-hover-white" title="Wikipedia"><i class="fa fa-wikipedia-w"></i></a>
		
	  </div> 
	</div>

    <div class="w3-container"  style="margin-top:60px;">
	<main>
      {% block content %}{% endblock %}
    </main>
	</div>
    <footer>
	  <div class="w3-bar w3-padding">
        <a href="#">
	      <button class="w3-button w3-hover-white fa fa-angle-double-up"></button>
	    </a>
	    <a href={% url 'ilm:index' %}>
          <button class="w3-button w3-hover-white w3-right w3-text-grey"><small>&#9400;&nbsp;2018 Kalev Härk</small></button>
	    </a>
      </div>
	</footer>
	<!-- jQuery teek -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	<!-- HighCharts skriptid -->
	<script src="https://code.highcharts.com/highcharts.js"></script>
	<script src="https://code.highcharts.com/highcharts-more.js"></script>
	<script src="https://code.highcharts.com/modules/exporting.js"></script>
	<script src="https://code.highcharts.com/modules/export-data.js"></script>
	<script src="https://code.highcharts.com/modules/windbarb.js"></script>
	<script src="{% static 'ilm/js/highcharts-regression.js' %}"></script>
	<!-- Äpi skriptid, kui vaja -->
	<script src="{% static 'ilm/js/ilm.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

ilm/templates/ilm/forecasts_quality_td.html
<td
        class="w3-{% if q == 100 %}green{% elif q >= 80 %}pale-green{% elif q >= 60 %}pale-yellow{% else %}pale-red{% endif %}"
        {% if ft %}title="ennustus: {{ ft|floatformat:1 }}°C - tegelik: {{ element.observed_temp|floatformat:1 }}°C&#10;ennustus: {{ fp|floatformat:1 }} mm - tegelik: {{ element.observed_prec|floatformat:1 }} mm"{% endif %}
>
    {{ q|floatformat:1 }}
</td>

ilm/templates/ilm/history.html
{% extends "ilm/ilm_base.html" %}
{% load static %}

{% block stylesheet %}
{% endblock %}

{% block javascript %}
	<script src="{% static 'ilm/js/ilm_history.js' %}"></script>
{% endblock %}

{% block title %}
  {{ block.super }} - ajalugu
{% endblock %}

{% block content %}
  <div class="w3-row">
    <div class="w3-half">
			<form id="frm1" action="{% url 'ilm:history' %}" method="post">
				{% csrf_token %}
				<table>
					<tr>
						<td>
							<div id="container_history_andmed" data-url="{% url 'ilm:container_history_andmed' %}"></div>
						</td>
						<td>
							{{ form.aasta }}
						</td>
						<td>
							{{ form.kuu }}
						</td>
						<td>
							{{ form.p2ev }}
						</td>
						<td>
							<button id="submit" type="submit"><i class="fa fa-search"></i></button>
							<image id="submitLoader" src="{% static 'ilm/img/ajax-loader.gif' %}"/>
						</td>
					</tr>
					<tr>
						<td>
							{{ form.non_field_errors }} {{ form.aasta.errors }} {{ form.kuu.errors }} {{ form.p2ev.errors }}
						</td>
					</tr>
				</table>
			</form>
		<div id="text"></div>
	</div>

  <div class="w3-row">
  </div>

  <div class="w3-row">
		<div id="loader"></div>
		<div class="w3-center" id="loaderDiv1">
			<img src={% static "ilm/img/ajax-loader-bar.gif" %} >
		</div>
		<div id="container_history_aasta" data-url="{% url 'ilm:container_history_aasta' %}" style="min-width: 300px; margin: 0 auto"></div>
  </div>
  <div class="w3-row">
    <div class="w3-half w3-mobile">
			<div class="w3-center" id="loaderDiv2">
				<img src="{% static 'ilm/img/ajax-loader-bar.gif' %}" >
			</div>
	  	<div id="container_history_kuud" data-url="{% url 'ilm:container_history_kuud' %}" style="min-width: 300px; margin: 0 auto"></div>
		</div>
		<div class="w3-half w3-mobile">
			<div class="w3-center" id="loaderDiv3">
				<img src="{% static 'ilm/img/ajax-loader-bar.gif' %}" >
			</div>
			<div id="container_history_kuu" data-url="{% url 'ilm:container_history_kuu' %}" style="min-width: 300px; margin: 0 auto"></div>
		</div>
  </div>
  <div class="w3-row">
    <div class="w3-half">
			<div class="w3-center" id="loaderDiv4">
				<img src={% static "ilm/img/ajax-loader-bar.gif" %} >
			</div>
			<div id="container_history_p2ev" data-url="{% url 'ilm:container_history_p2ev' %}" style="min-width: 300px; margin: 0 auto"></div>
		</div>
		<div class="w3-half">
			<div class="w3-center" id="loaderDiv5">
				<img src={% static "ilm/img/ajax-loader-bar.gif" %} >
			</div>
			<div id="container_history_p2evad" data-url="{% url 'ilm:container_history_p2evad' %}" style="min-width: 300px; margin: 0 auto"></div>
		</div>
  </div>
	<div class="w3-row">
		<div class="w3-half">
			<div class="w3-center" id="loaderDiv6">
				<img src={% static "ilm/img/ajax-loader-bar.gif" %} >
			</div>
			<div id="container_history_aastad" data-url="{% url 'ilm:container_history_aastad' %}" style="min-width: 300px; margin: 0 auto"></div>
		</div>
		<div class="w3-half">
			<div class="w3-center" id="loaderDiv7">
				<img src={% static "ilm/img/ajax-loader-bar.gif" %} >
			</div>
			<div id="container_history_kuud_aastatekaupa" data-url="{% url 'ilm:container_history_kuud_aastatekaupa' %}" style="min-width: 300px; margin: 0 auto"></div>
		</div>
  </div>

{% endblock %}

ilm/templates/ilm/index.html
{% extends "ilm/ilm_base.html" %}
{% load static %}
{% load ilm_extras %}

{% block stylesheet %}
  {#  <link rel="stylesheet" href="https://unpkg.com/tailwindcss@next/dist/tailwind.min.css">#}
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
{% endblock %}

{% block javascript %}
<script src="{% static 'ilm/js/swiped-events.js' %}"></script>
<script src="{% static 'ilm/js/ilm_mixed_ilmateade.js' %}"></script>
<script src="{% static 'ilm/js/ilm_mixed_ilmateade_mobile.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="w3-row w3-hide-small">
    {% include "ilm/mixed_ilmateade.html" %}
  </div>
  <div class="font-sans max-w-md mx-auto w3-hide-large w3-hide-medium">
    {% include "ilm/mixed_ilmateade_mobile.html" %}
  </div>
{% endblock %}

ilm/templates/ilm/mixed_ilmateade.html
{% load static %}
<div id="loader"></div>
<div
    id="container_mixed_ilmateade"
    class="animate-bottom"
    data-url="{% url 'ilm:mixed_ilmateade' %}"
    style="min-width: 400px; margin: 0 auto; display:none;">
</div>