ilm/urls.py
from django.urls import path, include
from . import views

app_name = 'ilm'
urlpatterns = [
    path('', views.index, name='index'),
    # path('mobile/', views.index_mobile, name='index_mobile'),
    path('history/', views.history, name='history'),
    path('forecasts/', views.forecasts, name='forecasts'),
    path('forecasts/<str:asukoht>/', views.forecasts, name='forecasts_with_asukoht'),
    # path('forecasts_yrno/', views.forecasts_yrno, name='forecasts_yrno'),
    path('forecasts_quality/', views.forecasts_quality, name='forecasts_quality'),
    path('maxmin/', views.maxmin, name='maxmin'),
    path('mixed_ilmateade/', views.mixed_ilmateade, name='mixed_ilmateade'),
    path('container_history_andmed/', views.container_history_andmed, name='container_history_andmed'),
    path('container_history_aasta/', views.container_history_aasta, name='container_history_aasta'),
    path('container_history_kuud/', views.container_history_kuud, name='container_history_kuud'),
    path('container_history_kuu/', views.container_history_kuu, name='container_history_kuu'),
    path('container_history_kuud_aastatekaupa/', views.container_history_kuud_aastatekaupa, name='container_history_kuud_aastatekaupa'),
    path('container_history_p2ev/', views.container_history_p2ev, name='container_history_p2ev'),
    path('container_history_p2evad/', views.container_history_p2evad, name='container_history_p2evad'),
    path('container_history_aastad/', views.container_history_aastad, name='container_history_aastad'),
    # path('pyimage/', PyImageView.as_view(), name='pyimage_view'),
]

kroonika/urls.py
# kroonika URL Configuration

from ajax_select import urls as ajax_select_urls

# from django.contrib.auth import views as auth_views
from django.conf import settings
# from django.conf.urls import handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

from .sitemaps import StaticViewSitemap, ArtikkelSitemap, IsikSitemap, OrganisatsioonSitemap, ObjektSitemap
from .routers import router
from wiki import views, specials

# sitemaps.xml
sitemaps = {
    'static': StaticViewSitemap,
    'lood': ArtikkelSitemap,
    'isikud': IsikSitemap,
    'asutised': OrganisatsioonSitemap,
    'kohad': ObjektSitemap
}

# schema_url_patterns = [
#     path('api/', include(router.urls)),
# ]

# API
schema_view = get_schema_view(
    title='Valga linna kroonika API',
    # url='https://valgalinn/api/',
    # patterns=schema_url_patterns
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.algus, name='algus'),
    path('info/', views.info, name='info'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')), # django-allauth
    path('ajax_select/', include(ajax_select_urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	path('api/', include(router.urls)),
    path('blog/', include('blog.urls'), name='blog'),
    path('kiri/', include('kiri.urls'), name='kiri'),
    path('ilm/', include('ilm.urls'), name='ilm'),
    path('inlineedit/', include('inlineedit.urls'), name='save'), # https://github.com/ptav/django-inlineedit
    path('docs/', include_docs_urls(title='Valga linna kroonika API')),
    path('markdownx/', include('markdownx.urls')),
    path('privacy/', views.privacy, name='privacy'),
    path('schema/', schema_view),
    path('wiki/', include('wiki.urls')),
    path('kaart/', views.kaart, name='kaart'),
    path('kaart/get_big_leaflet_map/', views.get_big_leaflet_map, name='get_big_leaflet_map'),
    path('kaart/<int:aasta>/', views.kaart, name='kaart'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('valga438/', specials.special_valga438, name='special_valga438'),
    # path('valga439/', specials.special_valga439, name='special_valga439'),
    # path('valga440/', specials.special_valga440, name='special_valga440'),
    # path('valga441/', specials.special_valga441, name='special_valga441'),
    # path('j6ul2020/', specials.special_j6ul2020, name='special_j6ul2020'),
    # path('j6ul2021/', specials.special_j6ul2021, name='special_j6ul2021'),
    # path('j6ul2022/', specials.special_j6ul2022, name='special_j6ul2022'),
    # path('j6ul2023/', specials.special_j6ul2023, name='special_j6ul2023'),
    # path('j6ul2024/', specials.special_j6ul2024, name='special_j6ul2024'),
    path('j6ul2025/', specials.special_j6ul2025, name='special_j6ul2025'),
    path('vgvk/', include('vgvk.urls')),
    path('raise_500_error/', views.raise_500_error, name='raise_500_error'), # http500 veateate testimiseks
    # path("__debug__/", include("debug_toolbar.urls")), # https://django-debug-toolbar.readthedocs.io
]

#error handling
handler500 = 'wiki.views.custom_500'

# Haldusliidese pealkirjad
admin.site.site_header = 'valgalinn.ee sisuhaldus'
admin.site.site_title = 'valgalinn.ee sisuhaldus'

# Serve static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve user uploaded media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/urls.py
"""
wiki urls definition
"""
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

# Objektivaated
from wiki.views import ArtikkelDetailView, IsikDetailView, OrganisatsioonDetailView, ObjektDetailView, KaardiobjektDetailView
# Filtreerimisvaated
from wiki.views import ArtikkelFilterView, IsikFilterView, OrganisatsioonFilterView, ObjektFilterView, KaardiobjektFilterView
# Loendivaated
from wiki.views import ArtikkelArchiveIndexView, ArtikkelYearArchiveView, ArtikkelMonthArchiveView, ArtikkelDayArchiveView
# Muutmisvaated
from wiki.views import ArtikkelUpdate, IsikUpdate, OrganisatsioonUpdate, ObjektUpdate, KaardiobjektUpdate
# API vaated
# from wiki.views import UserDetail, UserList

app_name = 'wiki'

urlpatterns = [
    path('', ArtikkelFilterView.as_view(), name='wiki_artikkel_filter'),
    path('get_algus_extra/', views.get_algus_extra, name='get_algus_extra'),
    path('<int:pk>-<str:slug>/', ArtikkelDetailView.as_view(), name='wiki_artikkel_detail'),
    # path('info/', views.info, name='info'),
    path('otsi/', views.otsi, name='otsi'),
    path('v6rdle/', views.v6rdle, name='v6rdle'),
    path('v6rdle/<str:model>/', views.v6rdle, name='v6rdle_model'),
    path('get_v6rdle_object/', views.get_v6rdle_object, name='get_v6rdle_object'),
    path('get_update_object_with_object/', views.get_update_object_with_object, name='get_update_object_with_object'),
    path('feedback/', views.feedback, name='feedback'),
    path('confirm_with_recaptcha/', views.confirm_with_recaptcha, name='confirm_with_recaptcha'),
    path('kroonika/', ArtikkelArchiveIndexView.as_view(), name='artikkel_index_archive'),
    path('kroonika/infinite/', views.artikkel_index_archive_infinite, name='artikkel_index_archive_infinite'),
    path('kroonika/<int:year>/', (cache_page(settings.CACHE_MIDDLEWARE_SECONDS)(ArtikkelYearArchiveView.as_view())), name='artikkel_year_archive'),
    path('kroonika/<int:year>/<int:month>/', ArtikkelMonthArchiveView.as_view(month_format='%m'), name='artikkel_month_archive'),
    path('kroonika/<int:year>/<int:month>/otheryears/', views.artikkel_month_archive_otheryears, name='artikkel_month_archive_otheryears'),
    path('kroonika/<int:year>/<int:month>/<int:day>/', ArtikkelDayArchiveView.as_view(month_format='%m'), name='artikkel_day_archive'),
    path('kroonika/mine_krono_kp', views.mine_krono_kp, name='mine_krono_kp'),
    path('kroonika/mine_krono_kuu', views.mine_krono_kuu, name='mine_krono_kuu'),
    # path('kroonika/mine_krono_aasta', views.mine_krono_aasta, name='mine_krono_aasta'),
    path('isik/', IsikFilterView.as_view(), name='wiki_isik_filter'),
    path('isik/<int:pk>-<str:slug>/', IsikDetailView.as_view(), name='wiki_isik_detail'),
    path('object_detail_seotud/<str:model>-<int:id>/', views.object_detail_seotud, name='wiki_object_detail_seotud'),
    path('object_detail_seotud_pildirida/<str:model>-<int:id>/', views.object_detail_seotud_pildirida, name='wiki_object_detail_seotud_pildirida'),
    path('get_object_data4tooltip/', views.get_object_data4tooltip, name='get_object_data4tooltip'),
    path('get_qrcode_from_uri/', views.get_qrcode_from_uri, name='get_qrcode_from_uri'),
    path('organisatsioon/', OrganisatsioonFilterView.as_view(), name='wiki_organisatsioon_filter'),
    path('organisatsioon/<int:pk>-<str:slug>/', OrganisatsioonDetailView.as_view(), name='wiki_organisatsioon_detail'),
    path('objekt/', ObjektFilterView.as_view(), name='wiki_objekt_filter'),
    path('objekt/<int:pk>-<str:slug>/', ObjektDetailView.as_view(), name='wiki_objekt_detail'),
    path('objekt/get_objekt_leaflet_combo/<int:objekt_id>/', views.get_objekt_leaflet_combo, name='get_objekt_leaflet_combo'),
    path('kaardiobjekt/', KaardiobjektFilterView.as_view(), name='wiki_kaardiobjekt_filter'),
    path('kaardiobjekt/<int:pk>/', KaardiobjektDetailView.as_view(), name='wiki_kaardiobjekt_detail'),
    path('kaardiobjekt/get_kaardiobjekt_leaflet/<int:kaardiobjekt_id>/', views.get_kaardiobjekt_leaflet, name='get_kaardiobjekt_leaflet'),
    path('kaardiobjekt/join_kaardiobjekt_with_objekt/<int:kaardiobjekt_id>-<int:objekt_id>/', views.join_kaardiobjekt_with_objekt, name='join_kaardiobjekt_with_objekt'),
    path('update/artikkel/<int:pk>', ArtikkelUpdate.as_view(), name='artikkel_update'),
    path('update/isik/<int:pk>', IsikUpdate.as_view(), name='isik_update'),
    path('update/organisatsioon/<int:pk>', OrganisatsioonUpdate.as_view(), name='organisatsioon_update'),
    path('update/objekt/<int:pk>', ObjektUpdate.as_view(), name='objekt_update'),
    path('update/kaardiobjekt/<int:pk>', KaardiobjektUpdate.as_view(), name='kaardiobjekt_update'),
    path('wiki_base_info/', views.wiki_base_info, name='wiki_base_info'),
    path('switch_vkj_ukj/<str:calendar_system>/', views.switch_vkj_ukj, name='switch_vkj_ukj'),
    # path('users/', UserList.as_view()),
    # path('users/<int:pk>/', UserDetail.as_view()),
    path('calendar_days_with_events_in_month/', views.calendar_days_with_events_in_month, name='calendar_days_with_events_in_month'),
]

wiki/templates/wiki/includes/algus_artiklid.html
{% load static %}
{% load wiki_extras %}
  <!-- Sel päeval sada aastat tagasi toimunud -->
  {% if andmed.sada_aastat_tagasi %}
    <h5>
      Täna 100 aastat tagasi...
    </h5>

    {% if andmed.isik.sada_aastat_tagasi %}
      <div style="padding-top: 0.5em;">
        {% for obj in andmed.isik.sada_aastat_tagasi %}
          {% if forloop.counter > 1 %}
            <br>
          {% endif %}
          <a class="hover-isik" href="{% url 'wiki:wiki_isik_detail' pk=obj.id slug=obj.slug %}">
            ...sündis <strong>{{ obj }}</strong>
            {% include 'wiki/includes/algus_pilt.html' with tyyp='portree' %}
          </a>
        {% endfor %}
      </div>
    {% endif %}
    {% if andmed.organisatsioon.sada_aastat_tagasi %}
      <div style="padding-top: 0.5em;">
        {% for obj in andmed.organisatsioon.sada_aastat_tagasi %}
          {% if forloop.counter > 1 %}
            <br>
          {% endif %}
          <a class="hover-organisatsioon" href="{% url 'wiki:wiki_organisatsioon_detail' pk=obj.id slug=obj.slug %}">
            ...asutati <strong>{{ obj }}</strong>
            {% include 'wiki/includes/algus_pilt.html' with tyyp='postkaart' %}
          </a>
        {% endfor %}
      </div>
    {% endif %}
    {% if andmed.objekt.sada_aastat_tagasi %}
      <div style="padding-top: 0.5em;">
        {% for obj in andmed.objekt.sada_aastat_tagasi %}
          {% if forloop.counter > 1 %}
            <br>
          {% endif %}
          <a class="hover-objekt" href="{% url 'wiki:wiki_objekt_detail' pk=obj.id slug=obj.slug %}">
            ...valmis <strong>{{ obj }}</strong>
            {% include 'wiki/includes/algus_pilt.html' with tyyp='postkaart' %}
          </a>
        {% endfor %}
      </div>
    {% endif %}
    {% if andmed.artikkel.sada_aastat_tagasi %}
      <div>
        {% for obj in andmed.artikkel.sada_aastat_tagasi %}
          {% if forloop.counter > 1 %}
            <br>
          {% endif %}
          <a class="hover-artikkel" href="{% url 'wiki:wiki_artikkel_detail' pk=obj.id slug=obj.slug %}">
            <strong>... </strong>{{ obj.body_text|truncatewords:10 }}
            {% include 'wiki/includes/algus_pilt.html' with tyyp='postkaart' %}
          </a>
        {% endfor %}
      </div>
    {% endif %}
  {% endif %}
  <!-- Sel päeval toimunud -->
  {% if andmed.artikkel.sel_p2eval %}
    <h5>
      <a
              style="text-decoration:none;"
              href="{% url 'wiki:artikkel_day_archive' day=p2ev month=kuu year=aasta %}"
              title="Näita kõiki {% now "j.m." %} ajaloos"
      >
        {% now "j.m." %} ajaloos <span class="w3-badge background-artikkel">{{ andmed.artikkel.sel_p2eval_kirjeid }}</span>
      </a>
    </h5>
    {% for obj in andmed.artikkel.sel_p2eval %}
      {% if forloop.counter > 1 %}
        <br>
      {% endif %}
      <strong>{% include 'wiki/includes/date_year.html' with obj=obj %}</strong>
      <a class="hover-artikkel" href="{% url 'wiki:wiki_artikkel_detail' pk=obj.id slug=obj.slug %}">
        {{ obj.body_text|truncatewords:10 }}
        {% include 'wiki/includes/algus_pilt.html' with tyyp='postkaart' %}
      </a>
      {# Kui kirjed rohkem kui artikleid_max_split, siis hakime artikleid_max_split_half+1+artikleid_max_split_half  #}
      {% if andmed.artikkel.sel_p2eval_kirjeid > andmed.artikkel.artikleid_max_split %}
        {% if forloop.counter == andmed.artikkel.artikleid_max_split_half %}
          <br>
          <a
                  style="text-decoration:none;"
                  href="{% url 'wiki:artikkel_day_archive' day=p2ev month=kuu year=aasta %}"
                  title="Näita kõiki {% now "j.m." %} ajaloos"
          >
            [ . . . ]
          </a>
        {% endif %}
        {% if forloop.counter == andmed.artikkel.artikleid_max_split_half|add:"1" %}
          <br>
          <a
                  style="text-decoration:none;"
                  href="{% url 'wiki:artikkel_day_archive' day=p2ev month=kuu year=aasta %}"
                  title="Näita kõiki {% now "j.m." %} ajaloos"
          >
            [ . . . ]
          </a>
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if andmed.artikkel.sel_p2eval_kirjeid > andmed.artikkel.artikleid_max_split %}
      <p>
        <a class="hover-artikkel" href="{% url 'wiki:artikkel_day_archive' day=p2ev month=kuu year=aasta %}">
          Näita kõiki <em>{% now "j.m." %} ajaloos</em> ({{ andmed.artikkel.sel_p2eval_kirjeid }})
        </a>
      </p>
    {% endif %}
  {% endif %}
  <!-- Sel kuul toimunud -->
  {% if andmed.artikkel.sel_kuul %}
    <h5>
      <a
              style="text-decoration:none;"
              href="{% url 'wiki:artikkel_month_archive' month=kuu year=aasta %}"
              title="Näita kõiki {% include 'wiki/includes/kuul.html' with kuu=kuu %} ajaloos"
      >
        {% include 'wiki/includes/kuul.html' with kuu=kuu %} ajaloos <span class="w3-badge background-artikkel">{{ andmed.artikkel.sel_kuul_kirjeid }}</span>
      </a>
    </h5>
    {% for obj in andmed.artikkel.sel_kuul %}
      {% if forloop.counter > 1 %}
        <br>
      {% endif %}
      <strong>{% include 'wiki/includes/date_year.html' with obj=obj %}</strong>
      <a class="hover-artikkel" href="{% url 'wiki:wiki_artikkel_detail' pk=obj.id slug=obj.slug %}">
        {{ obj.body_text|truncatewords:10 }}
      </a>
      {# Kui kirjed rohkem kui artikleid_max_split, siis hakime artikleid_max_split_half+1+artikleid_max_split_half  #}
      {% if andmed.artikkel.sel_kuul_kirjeid > andmed.artikkel.artikleid_max_split %}
        {% if forloop.counter == andmed.artikkel.artikleid_max_split_half %}
          <br>
          <a
                  style="text-decoration:none;"
                  href="{% url 'wiki:artikkel_month_archive' month=kuu year=aasta %}"
                  title="Näita kõiki {% include 'wiki/includes/kuul.html' with kuu=kuu %} ajaloos"
          >
            [ . . . ]
          </a>
        {% endif %}
        {% if forloop.counter == andmed.artikkel.artikleid_max_split_half|add:"1" %}
          <br>
          <a
                  style="text-decoration:none;"
                  href="{% url 'wiki:artikkel_month_archive' month=kuu year=aasta %}"
                  title="Näita kõiki {% include 'wiki/includes/kuul.html' with kuu=kuu %} ajaloos"
          >
            [ . . . ]
          </a>
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if andmed.artikkel.sel_kuul_kirjeid > andmed.artikkel.artikleid_max_split %}
      <p>
        <a class="hover-artikkel" href="{% url 'wiki:artikkel_month_archive' month=kuu year=aasta %}">
          Näita kõiki <em>{% include 'wiki/includes/kuul.html' with kuu=kuu %} ajaloos</em> ({{ andmed.artikkel.sel_kuul_kirjeid }})
        </a>
      </p>
    {% endif %}
  {% endif %}
  <!-- top10 -->
  {% if andmed.artikkel.loetumad %}
    <h5>
      loetumad
    </h5>
    {% for obj in andmed.artikkel.loetumad %}
      {% if forloop.counter > 1 %}
        <br>
      {% endif %}
      <strong>{% include 'wiki/includes/date_year.html' with obj=obj %}</strong>
{#      <a class="hover-artikkel" href="{% url 'wiki:artikkel_year_archive' year=obj.hist_year %}" #}
{#        <strong>{{ obj.hist_year }}</strong>: #}
{#      </a> #}
      <a class="hover-artikkel" href="{% url 'wiki:wiki_artikkel_detail' pk=obj.id slug=obj.slug %}">
        {{ obj.body_text|truncatewords:10 }}
      </a>
      <small>&nbsp;{{ obj.total_accessed }} vaatamist</small>
    {% endfor %}
  {% endif %}

wiki/templates/wiki/includes/algus_head.html
{% load wiki_extras %}
<div class="w3-quarter">
  <a
      class="w3-tooltip"
      style="text-decoration: none;"
      href="{% url 'wiki:wiki_artikkel_filter' %}"
  >
    <div class="w3-container w3-round background-artikkel w3-padding-16 w3-hover-white">
      <div class="w3-left">
        <i class="fa fa-comment w3-xxxlarge"></i>

      </div>
      <div class="w3-hide-medium w3-right">
        <h4>{% model_name_artikkel %} ({{ andmed.artikkel.kirjeid }})</h4>
      </div>
      <div class="w3-hide-large w3-hide-small w3-right ">
        <h6>{% model_name_artikkel %} ({{ andmed.artikkel.kirjeid }})</h6>
      </div>

    </div>
  </a>
</div>
<div class="w3-quarter">
  <a style="text-decoration: none;" href="{% url 'wiki:wiki_isik_filter' %}">
    <div class="w3-container w3-round background-isik w3-padding-16 w3-hover-white">
      <div class="w3-left">
        <i class="fa fa-address-card-o w3-xxxlarge"></i>
      </div>
      <div class="w3-hide-medium w3-right">
        <h4>{% model_name_isik %} ({{ andmed.isik.kirjeid }})</h4>
      </div>
      <div class="w3-hide-large w3-hide-small w3-right ">
        <h6>{% model_name_isik %} ({{ andmed.isik.kirjeid }})</h6>
      </div>
    </div>
  </a>
</div>
<div class="w3-quarter">
  <a class="w3-tooltip" style="text-decoration: none;" href="{% url 'wiki:wiki_organisatsioon_filter' %}">
    <div class="w3-container w3-round background-organisatsioon w3-padding-16 w3-hover-white">
      <div class="w3-left">
        <i class="fa fa-group w3-xxxlarge"></i>
      </div>
      <div class="w3-hide-medium w3-right">
        <h4>{% model_name_organisatsioon %} ({{ andmed.organisatsioon.kirjeid }})</h4>
      </div>
      <div class="w3-hide-large w3-hide-small w3-right ">
        <h6>{% model_name_organisatsioon %} ({{ andmed.organisatsioon.kirjeid }})</h6>
      </div>
    </div>
  </a>
</div>
<div class="w3-quarter">
  <a
      class="w3-tooltip"
      style="text-decoration: none;"
      href="{% url 'wiki:wiki_objekt_filter' %}"
  >
    <div class="w3-container w3-round background-objekt w3-padding-16 w3-hover-white">
      <div class="w3-left">
        <i class="fa fa-bank w3-xxxlarge"></i>
      </div>
      <div class="w3-hide-medium w3-right">
        <h4>{% model_name_objekt %} ({{ andmed.objekt.kirjeid }})</h4>
      </div>
      <div class="w3-hide-large w3-hide-small w3-right ">
        <h6>{% model_name_objekt %} ({{ andmed.objekt.kirjeid }})</h6>
      </div>
    </div>
  </a>
</div>

wiki/templates/wiki/includes/object_detail_map.html
<!-- Sisukaardi kaardiosa-->
<div
        class="w3-margin-right w3-center w3-padding-16"
        style="display: {% if seotud_kaardiobjektid %}block{% else %}none{% endif %}"
>
  {% include 'wiki/includes/div_loader_book.html' with n=2 %}
  <div
        id="get_objekt_leaflet_combo"
        data-url="{% url 'wiki:get_objekt_leaflet_combo' object.id %}"
  ></div>
  {% if user.is_authenticated %}
    <div class="w3-padding-16">
    <ul class="no-bullets">
      {% for obj in seotud_kaardiobjektid %}
        <li>
          <a
              class="hover-artikkel"
              href="{% url 'wiki:wiki_kaardiobjekt_detail' pk=obj.id %}"
            >
            {{ obj }}
          </a>
        </li>
      {% endfor %}
    </ul>
    </div>
  {% endif %}
</div>

{% if seotud_kaardiobjektid %}
  <script>
    function get_objekt_leaflet_combo() {
      // Küsime andmed ja näitame kaarti
      $.ajax({
        url: $("#get_objekt_leaflet_combo").attr("data-url"),
        dataType: 'text',
        timeout: 300000,
        beforeSend: function() {
          $("#loaderDiv2").show();
        },
        success: function (data) {
          if (data) {
              document.getElementById("get_objekt_leaflet_combo").innerHTML = data;
            }
          },
        error: function (XMLHttpRequest, textstatus, errorThrown) {
          console.log(textstatus);
        },
      complete: function () {
        $("#loaderDiv2").hide();
      }
      });
    }

    $(document).ready(function() {
      get_objekt_leaflet_combo();
    });
  </script>
{% endif %}

wiki/templates/wiki/includes/object_mainitud_artiklites2.html
{% load wiki_extras %}
{# Loetelu seotud artiklinumbritest #}
{% if artiklid %}
  &nbsp;mainitud:
  {% for obj in artiklid %}
    &nbsp;
    <a class="hover-artikkel tooltip-content w3-round" href="{% url 'wiki:wiki_artikkel_detail' pk=obj.id slug=obj.slug %}">
      <span
              title={{ obj.hist_year }}
              data-model='Artikkel'
              data-id='{{ obj.id }}'
              id='Artikkel_{{ obj.id }}_{% get_uuid %}'>
        {{ obj.hist_year }}
      </span>
    </a>
  {% endfor %}
{% endif %}

wiki/templates/wiki/includes/seotud_artiklikaudu_objektid.html
{% load wiki_extras %}
{% if seotud_objektid_artiklikaudu %}
  <!-- Loend seotud objektidest, mis on nimetatud samas artiklis -->
  <div>
    <h5>
      <i class="fa fa-chain w3-xlarge text-objekt"></i>
      {% model_name_objekt %}, millega koos mainitud lugudes:<br>
    </h5>
    {% for item, obj in seotud_objektid_artiklikaudu.items %}
      {% if forloop.counter > 1 %}
        <br>
      {% endif %}
      <a class="hover-objekt tooltip-content" href="{% url 'wiki:wiki_objekt_detail' pk=obj.id slug=obj.slug %}">
{#        <strong>{{ obj.nimi }}</strong>#}
        <span
              title='{{ obj.nimi }}'
              data-model='Objekt'
              data-id='{{ obj.id }}'
              id='Objekt_{{ obj.id }}_seotud_kaudu_objektid'>
          {{ obj.nimi }}
        </span>
      </a>
      &nbsp;&ndash;&nbsp;
      {% include 'wiki/includes/seotud_artiklikaudu_artiklid.html' with model_id='objekt' %}
    {% endfor %}
  </div>
{% endif %}

wiki/templates/wiki/includes/seotud_isikud_artiklikaudu.html
{% if seotud_isikud_artiklikaudu %}
<!-- Loend seotud isikutest, mis on nimetatud samas artiklis -->
  <div>
		<h5>
			<i class="fa fa-chain w3-xlarge text-isik"></i>
			Isikud, kellega koos mainitud sissekannetes:
		</h5>
		{% for seotud_isik, obj in seotud_isikud_artiklikaudu.items %}
			{% if forloop.counter > 1 %}
				<br>
			{% endif %}
			<a class="hover-isik" href="{% url 'wiki:wiki_isik_detail' pk=obj.id slug=obj.slug %}">
				<strong>{{ obj.nimi }}</strong>
			</a>
			&nbsp;&ndash;&nbsp;
			{% include 'wiki/includes/seotud_artiklikaudu_artiklid.html' %}
    {% endfor %}
  </div>
{% endif %}