blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    # path("<int:pk>/", views.blog_detail, name="blog_detail"),
    # path("<int:pk>/", views.blog_index, name="blog_detail"),
    path("<str:slug>/", views.blog_index, name="blog_detail"),
]

ilm/urls.py
from django.urls import path, include
from . import views

app_name = 'ilm'
urlpatterns = [
    path('', views.index, name='index'),
    # path('mobile/', views.index_mobile, name='index_mobile'),
    path('history/', views.history, name='history'),
    path('forecasts/', views.forecasts, name='forecasts'),
    path('forecasts/<str:asukoht>/', views.forecasts, name='forecasts_with_asukoht'),
    # path('forecasts_yrno/', views.forecasts_yrno, name='forecasts_yrno'),
    path('forecasts_quality/', views.forecasts_quality, name='forecasts_quality'),
    path('maxmin/', views.maxmin, name='maxmin'),
    path('mixed_ilmateade/', views.mixed_ilmateade, name='mixed_ilmateade'),
    path('container_history_andmed/', views.container_history_andmed, name='container_history_andmed'),
    path('container_history_aasta/', views.container_history_aasta, name='container_history_aasta'),
    path('container_history_kuud/', views.container_history_kuud, name='container_history_kuud'),
    path('container_history_kuu/', views.container_history_kuu, name='container_history_kuu'),
    path('container_history_kuud_aastatekaupa/', views.container_history_kuud_aastatekaupa, name='container_history_kuud_aastatekaupa'),
    path('container_history_p2ev/', views.container_history_p2ev, name='container_history_p2ev'),
    path('container_history_p2evad/', views.container_history_p2evad, name='container_history_p2evad'),
    path('container_history_aastad/', views.container_history_aastad, name='container_history_aastad'),
    # path('pyimage/', PyImageView.as_view(), name='pyimage_view'),
]

kroonika/urls.py
# kroonika URL Configuration

from ajax_select import urls as ajax_select_urls

# from django.contrib.auth import views as auth_views
from django.conf import settings
# from django.conf.urls import handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

from .sitemaps import StaticViewSitemap, ArtikkelSitemap, IsikSitemap, OrganisatsioonSitemap, ObjektSitemap
from .routers import router
from wiki import views, specials

# sitemaps.xml
sitemaps = {
    'static': StaticViewSitemap,
    'lood': ArtikkelSitemap,
    'isikud': IsikSitemap,
    'asutised': OrganisatsioonSitemap,
    'kohad': ObjektSitemap
}

# schema_url_patterns = [
#     path('api/', include(router.urls)),
# ]

# API
schema_view = get_schema_view(
    title='Valga linna kroonika API',
    # url='https://valgalinn/api/',
    # patterns=schema_url_patterns
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.algus, name='algus'),
    path('info/', views.info, name='info'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')), # django-allauth
    path('ajax_select/', include(ajax_select_urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	path('api/', include(router.urls)),
    path('blog/', include('blog.urls'), name='blog'),
    path('kiri/', include('kiri.urls'), name='kiri'),
    path('ilm/', include('ilm.urls'), name='ilm'),
    path('inlineedit/', include('inlineedit.urls'), name='save'), # https://github.com/ptav/django-inlineedit
    path('docs/', include_docs_urls(title='Valga linna kroonika API')),
    path('markdownx/', include('markdownx.urls')),
    path('privacy/', views.privacy, name='privacy'),
    path('schema/', schema_view),
    path('wiki/', include('wiki.urls')),
    path('kaart/', views.kaart, name='kaart'),
    path('kaart/get_big_leaflet_map/', views.get_big_leaflet_map, name='get_big_leaflet_map'),
    path('kaart/<int:aasta>/', views.kaart, name='kaart'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('valga438/', specials.special_valga438, name='special_valga438'),
    # path('valga439/', specials.special_valga439, name='special_valga439'),
    # path('valga440/', specials.special_valga440, name='special_valga440'),
    # path('valga441/', specials.special_valga441, name='special_valga441'),
    # path('j6ul2020/', specials.special_j6ul2020, name='special_j6ul2020'),
    # path('j6ul2021/', specials.special_j6ul2021, name='special_j6ul2021'),
    # path('j6ul2022/', specials.special_j6ul2022, name='special_j6ul2022'),
    # path('j6ul2023/', specials.special_j6ul2023, name='special_j6ul2023'),
    # path('j6ul2024/', specials.special_j6ul2024, name='special_j6ul2024'),
    path('j6ul2025/', specials.special_j6ul2025, name='special_j6ul2025'),
    path('vgvk/', include('vgvk.urls')),
    path('raise_500_error/', views.raise_500_error, name='raise_500_error'), # http500 veateate testimiseks
    # path("__debug__/", include("debug_toolbar.urls")), # https://django-debug-toolbar.readthedocs.io
]

#error handling
handler500 = 'wiki.views.custom_500'

# Haldusliidese pealkirjad
admin.site.site_header = 'valgalinn.ee sisuhaldus'
admin.site.site_title = 'valgalinn.ee sisuhaldus'

# Serve static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve user uploaded media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/urls.py
"""
wiki urls definition
"""
from django.conf import settings
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

# Objektivaated
from wiki.views import ArtikkelDetailView, IsikDetailView, OrganisatsioonDetailView, ObjektDetailView, KaardiobjektDetailView
# Filtreerimisvaated
from wiki.views import ArtikkelFilterView, IsikFilterView, OrganisatsioonFilterView, ObjektFilterView, KaardiobjektFilterView
# Loendivaated
from wiki.views import ArtikkelArchiveIndexView, ArtikkelYearArchiveView, ArtikkelMonthArchiveView, ArtikkelDayArchiveView
# Muutmisvaated
from wiki.views import ArtikkelUpdate, IsikUpdate, OrganisatsioonUpdate, ObjektUpdate, KaardiobjektUpdate
# API vaated
# from wiki.views import UserDetail, UserList

app_name = 'wiki'

urlpatterns = [
    path('', ArtikkelFilterView.as_view(), name='wiki_artikkel_filter'),
    path('get_algus_extra/', views.get_algus_extra, name='get_algus_extra'),
    path('<int:pk>-<str:slug>/', ArtikkelDetailView.as_view(), name='wiki_artikkel_detail'),
    # path('info/', views.info, name='info'),
    path('otsi/', views.otsi, name='otsi'),
    path('v6rdle/', views.v6rdle, name='v6rdle'),
    path('v6rdle/<str:model>/', views.v6rdle, name='v6rdle_model'),
    path('get_v6rdle_object/', views.get_v6rdle_object, name='get_v6rdle_object'),
    path('get_update_object_with_object/', views.get_update_object_with_object, name='get_update_object_with_object'),
    path('feedback/', views.feedback, name='feedback'),
    path('confirm_with_recaptcha/', views.confirm_with_recaptcha, name='confirm_with_recaptcha'),
    path('kroonika/', ArtikkelArchiveIndexView.as_view(), name='artikkel_index_archive'),
    path('kroonika/infinite/', views.artikkel_index_archive_infinite, name='artikkel_index_archive_infinite'),
    path('kroonika/<int:year>/', (cache_page(settings.CACHE_MIDDLEWARE_SECONDS)(ArtikkelYearArchiveView.as_view())), name='artikkel_year_archive'),
    path('kroonika/<int:year>/<int:month>/', ArtikkelMonthArchiveView.as_view(month_format='%m'), name='artikkel_month_archive'),
    path('kroonika/<int:year>/<int:month>/otheryears/', views.artikkel_month_archive_otheryears, name='artikkel_month_archive_otheryears'),
    path('kroonika/<int:year>/<int:month>/<int:day>/', ArtikkelDayArchiveView.as_view(month_format='%m'), name='artikkel_day_archive'),
    path('kroonika/mine_krono_kp', views.mine_krono_kp, name='mine_krono_kp'),
    path('kroonika/mine_krono_kuu', views.mine_krono_kuu, name='mine_krono_kuu'),
    # path('kroonika/mine_krono_aasta', views.mine_krono_aasta, name='mine_krono_aasta'),
    path('isik/', IsikFilterView.as_view(), name='wiki_isik_filter'),
    path('isik/<int:pk>-<str:slug>/', IsikDetailView.as_view(), name='wiki_isik_detail'),
    path('object_detail_seotud/<str:model>-<int:id>/', views.object_detail_seotud, name='wiki_object_detail_seotud'),
    path('object_detail_seotud_pildirida/<str:model>-<int:id>/', views.object_detail_seotud_pildirida, name='wiki_object_detail_seotud_pildirida'),
    path('get_object_data4tooltip/', views.get_object_data4tooltip, name='get_object_data4tooltip'),
    path('get_qrcode_from_uri/', views.get_qrcode_from_uri, name='get_qrcode_from_uri'),
    path('organisatsioon/', OrganisatsioonFilterView.as_view(), name='wiki_organisatsioon_filter'),
    path('organisatsioon/<int:pk>-<str:slug>/', OrganisatsioonDetailView.as_view(), name='wiki_organisatsioon_detail'),
    path('objekt/', ObjektFilterView.as_view(), name='wiki_objekt_filter'),
    path('objekt/<int:pk>-<str:slug>/', ObjektDetailView.as_view(), name='wiki_objekt_detail'),
    path('objekt/get_objekt_leaflet_combo/<int:objekt_id>/', views.get_objekt_leaflet_combo, name='get_objekt_leaflet_combo'),
    path('kaardiobjekt/', KaardiobjektFilterView.as_view(), name='wiki_kaardiobjekt_filter'),
    path('kaardiobjekt/<int:pk>/', KaardiobjektDetailView.as_view(), name='wiki_kaardiobjekt_detail'),
    path('kaardiobjekt/get_kaardiobjekt_leaflet/<int:kaardiobjekt_id>/', views.get_kaardiobjekt_leaflet, name='get_kaardiobjekt_leaflet'),
    path('kaardiobjekt/join_kaardiobjekt_with_objekt/<int:kaardiobjekt_id>-<int:objekt_id>/', views.join_kaardiobjekt_with_objekt, name='join_kaardiobjekt_with_objekt'),
    path('update/artikkel/<int:pk>', ArtikkelUpdate.as_view(), name='artikkel_update'),
    path('update/isik/<int:pk>', IsikUpdate.as_view(), name='isik_update'),
    path('update/organisatsioon/<int:pk>', OrganisatsioonUpdate.as_view(), name='organisatsioon_update'),
    path('update/objekt/<int:pk>', ObjektUpdate.as_view(), name='objekt_update'),
    path('update/kaardiobjekt/<int:pk>', KaardiobjektUpdate.as_view(), name='kaardiobjekt_update'),
    path('wiki_base_info/', views.wiki_base_info, name='wiki_base_info'),
    path('switch_vkj_ukj/<str:calendar_system>/', views.switch_vkj_ukj, name='switch_vkj_ukj'),
    # path('users/', UserList.as_view()),
    # path('users/<int:pk>/', UserDetail.as_view()),
    path('calendar_days_with_events_in_month/', views.calendar_days_with_events_in_month, name='calendar_days_with_events_in_month'),
]

wiki/templates/wiki/wiki_base/wiki_base_body_footer.html
{% load wiki_extras %}
<div class="w3-bar">
  <a href="#">
    <button class="w3-button w3-hover-white fa fa-angle-double-up"></button>
  </a>
  {# FB #}
  <div
      class="fb-like"
      data-href="http://valgalinn.ee"
      data-width=""
      data-layout="button_count"
      data-action="like"
      data-size="small"
      data-show-faces="true"
      data-share="true"
      style="vertical-align: bottom;"
  >
  </div>
  {# Autoriõigused #}
  <a
      rel="license"
      href="http://creativecommons.org/licenses/by-sa/4.0/">
    <img
        alt="Creative Commonsi litsents"
        style="border-width:0"
        src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png"
    />
  </a>
  <br class="w3-hide-large">
  <small class="w3-hide-small">
    "<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Valga linna kroonika</span>" on antud Creative Commonsi litsentsi "
    <a
        rel="license"
        href="http://creativecommons.org/licenses/by-sa/4.0/">Autorile viitamine + Jagamine samadel tingimustel 4.0 Rahvusvaheline
    </a>" alla.
  </small>
  <a href="{% url 'info' %}">
    <button class="w3-button w3-hover-white w3-right w3-text-grey">
      <small>&#9400;&nbsp;2018-{% now "Y" %} {% kalev %}</small>
    </button>
  </a>
</div>

wiki/templates/wiki/wiki_base/wiki_base_body_messages.html
<div>
  {% if messages %}
    <ul class="messagelist">
    {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>

wiki/templates/wiki/wiki_base/wiki_base_body_search_small.html
{% if not searchsmallwidgethidden %}
  <div
          id="search-small-widget"
          class="w3-padding w3-hide-medium w3-hide-large"
  >
    <form
        autocomplete="on"
        id="search"
        method="GET"
        action="{% url 'wiki:otsi' %}"
    >
      {% csrf_token %}
      <label for="search-input">Otsi:</label>
      <input
          aria-label="Otsi"
          id="search-input"
          name="q"
          placeholder="Sõna või fraas..."
          type="text"
          class="w3-round"
      >
      <button
          class="w3-button w3-round"
          type="submit"
          id="searchsubmit_small"
          title="Otsi valitud fraasi järgi">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24">
          <path d="M23.809 21.646l-6.205-6.205c1.167-1.605 1.857-3.579 1.857-5.711 0-5.365-4.365-9.73-9.731-9.73-5.365 0-9.73 4.365-9.73 9.73 0 5.366 4.365 9.73 9.73 9.73 2.034 0 3.923-.627 5.487-1.698l6.238 6.238 2.354-2.354zm-20.955-11.916c0-3.792 3.085-6.877 6.877-6.877s6.877 3.085 6.877 6.877-3.085 6.877-6.877 6.877c-3.793 0-6.877-3.085-6.877-6.877z"/>
        </svg>
      </button>
    </form>
  </div>
{% endif %}

wiki/templates/wiki/wiki_base/wiki_base_facebook_plugin.html
<div id="fb-root"></div>
<script
        async
        defer
        crossorigin="anonymous"
        src="https://connect.facebook.net/et_EE/sdk.js#xfbml=1&version=v14.0&appId=275987973680424&autoLogAppEvents=1"
        nonce="hLQIXwgB"
></script>

wiki/templates/wiki/wiki_base/wiki_base_json-ld.html
{#object = detailview 'object'#}
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type":"WebSite",
        "@id":"{{ request.scheme }}://{{ request.site }}/#website",
        "url":"{{ request.scheme }}://{{ request.site }}/",
        "name":"Valga linna kroonika",
        "inLanguage":"et",
        "potentialAction":
          {
            "@type":"SearchAction",
            "target":"{{ request.scheme }}://{{ request.site }}{% url 'wiki:otsi' %}?q={search_term_string}",
            "query-input":"required name=search_term_string"
          }
      },
      {
        "@type":"WebPage",
        "@id":"{{ request.build_absolute_uri }}#webpage",
        "url":"{{ request.build_absolute_uri }}",
        "name":"Valga linna kroonika",
        "isPartOf":
          {
            "@id":"{{ request.scheme }}://{{ request.site }}/#website"
          },
        "inLanguage":"et",
        {% if object %}
          "datePublished":"{{ object.inp_date|date:'c' }}",
          "dateModified":"{{ object.mod_date|date:'c' }}"
        {% else %}
          "datePublished":"{% now 'c' %}",
          "dateModified":"{% now 'c' %}"
        {% endif %}
      }
    ]
  }
</script>

wiki/templates/wiki/wiki_base/wiki_base_nav_bar_accounts.html
{% load socialaccount %}
{% if user.is_authenticated %}
  {% if user.is_staff %}
    <a
        href="{% url 'admin:index' %}"
        class="w3-bar-item w3-button w3-hide-small w3-text-grey w3-hover-white w3-right w3-round"
        title="Admin">
      <i class="fa fa-cog"></i>
    </a>
  {% else %}
    <a
        href="{% url 'account_email' %}"
        class="w3-bar-item w3-button w3-hide-small w3-text-grey w3-hover-white w3-right w3-round"
        title="Muuda {{ user.username }} kontaktandmeid">
      <i class="fa fa-user"></i>
    </a>
  {% endif %}
{#  <a#}
{#      href="{% url 'account_logout' %}?next={{ request.path | urlencode }}"#}
{#      class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-text-grey w3-hover-white w3-right"#}
{#      title="Logi välja">{{ user.first_name }}&nbsp;<i class="fa fa-sign-out"></i>#}
{#  </a>#}
  <form method="post" action="{% url 'account_logout' %}">
    {% csrf_token %}
    {% if redirect_field_value %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
    {% endif %}
    <button
            class="w3-bar-item w3-button w3-text-grey w3-hover-white w3-right w3-round"
            type="submit"
            title="Logi välja kasutaja {{ user.username }}"
    >
      {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %} <i class="fa fa-sign-out"></i>
    </button>
  </form>
{% else %}
  <a
      href="{% url 'account_signup' %}?next={{ request.path }}"
      class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-text-grey w3-hover-white w3-right w3-round"
      title="Registreeri">
    <i class="fa fa-user-plus"></i>
  </a>
  <a
      href="{% url 'account_login' %}?next={{ request.path }}"
      class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-text-grey w3-hover-white w3-right w3-round"
      title="Logi sisse">
    <i class="fa fa-sign-in"></i>
  </a>
{% endif %}

wiki/templates/wiki/wiki_base/wiki_base_nav_bar_calendar_system_choice.html
<div id="div_ukjvkj"  class="w3-hide-small w3-hide-medium w3-right" style="visibility:hidden;">
  <label class="rocker rocker-small" title="vana või uus kalender?"><input type="checkbox" id="checkbox_ukjvkj">
    <span class="switch-left">ukj</span>
    <span class="switch-right">vkj</span>
  </label>
</div>

wiki/templates/wiki/wiki_base/wiki_base_nav_bar_large.html
{% load static %}
{% load wiki_extras %}
<div
        class="w3-bar w3-left-align w3-large"
        id="wiki_base_info"
        data-url="{% url 'wiki:wiki_base_info' %}"
>
  {# Logo + link avalehele #}
  <a
          href="{% url 'algus' %}"
          title="Valga linna kroonika avalehele"
          class="w3-bar-item w3-button w3-hover-white w3-round">
    <img
            src="{% static 'wiki/favicon-32x32.png' %}"
            style='max-height:22px;'
            alt="valgalinn.ee logo"
    >
  </a>
  <a
      href="{% url 'algus' %}"
      class="w3-bar-item w3-button w3-hover-white w3-hide-small w3-round">
    <i
        id="wiki_start_icon"
        style="display: inline-block; margin-right: 10px;"
        class="text-artikkel fa fa-leanpub"
    >
    </i>
    <span class="w3-hide-small">Valga linna kroonika </span>
    <span class="w3-red">{% server_type %}</span>
  </a>

  {# Search on large screens #}
  <a
      href="{% url 'wiki:otsi' %}"
      title="Otsi valitud fraasi järgi"
      class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-round">
    <i
        id="wiki_search_icon"
        class="fa fa-search"
    >
    </i>
  </a>

  {# Tagasiside saatmiseks #}
  <a
      class="w3-bar-item w3-button w3-hover-white w3-round"
      id="wiki_base_feedback"
      title="Märkasid viga või oskad täiendada?"
      onclick="showFeedback()">
    <i class="fa fa-bug"></i>
  </a>

  {# Lingid erilehtedele #}
  <a
      href="{% url 'kaart' %}"
      class="w3-bar-item w3-button w3-hover-white w3-round"
      title="Ajaloolised kaardid">
    <i class="fa fa-map-o"></i>
  </a>
  <a
      href="{% url 'info' %}"
      class="w3-bar-item w3-button w3-hide-small w3-hover-white w3-round"
      title="Projektist">
    <i class="fa fa-info"></i>
  </a>
  <a
      href="{% url 'blog:blog_index' %}"
      id="wiki_base_blog"
      class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-hover-white w3-round"
      title="Blogi">
    <i class="{% icon_artikkel %}s-o"></i>
  </a>
  <a
      href="{% url 'ilm:index' %}"
      class="w3-bar-item w3-button w3-hover-white w3-round"
      title="Valga linna ilm">
    <i class="fa fa-thermometer"></i>
  </a>
  <a
      href="https://et.wikipedia.org/wiki/Valga_(Liivimaa)"
      target="blank"
      class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-hover-white w3-round"
      title="Valga linn Wikipedia">
    <i class="fa fa-wikipedia-w"></i>
  </a>
  <a
      href="https://www.facebook.com/valgalinn/"
      target="blank"
      class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-hover-white w3-round"
      title="Valga linn Facebook">
    <i class="fa fa-facebook-official"></i>
  </a>
  <a
      href="https://www.instagram.com/valgalinn/"
      target="blank"
      class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-hover-white w3-round"
      title="Valga linn Instagram">
    <i class="fa fa-instagram"></i>
  </a>
  <a
      id="rightMenuLink"
      href="javascript:void(0)"
      class="w3-bar-item w3-button w3-hide-large w3-right w3-round"
      onclick="toggleRightMenu()">
    &#9776;
  </a>

  {# Kasutaja ja adminlingid #}
  {% include 'wiki/wiki_base/wiki_base_nav_bar_accounts.html' %}

  <!-- Kalendrivaliku nupp -->
  {% include 'wiki/wiki_base/wiki_base_nav_bar_calendar_system_choice.html' %}
</div>

wiki/templates/wiki/wiki_base/wiki_base_nav_bar_small.html
{% load wiki_extras %}
<div
        class="w3-bar-block w3-light-gray w3-hide w3-hide-large"
        id="rightMenu">
  <a
          href="{% url 'wiki:otsi' %}"
        class="w3-bar-item w3-button">
    <i class="fa fa-search"></i>
    <span class="bar-item-text-with-icon">Otsi...</span>
  </a>
  <a
          id="wiki_base_feedback_nav_bar_small"
          onclick="showFeedback()"
          class="w3-bar-item w3-button"
  >
    <i class="fa fa-bug"></i>
    <span class="bar-item-text-with-icon">Vigadest teatamine</span>
  </a>
  <a
          href="{% url 'kaart' %}"
          class="w3-bar-item w3-button"
  >
    <i class="fa fa-map-o"></i>
    <span class="bar-item-text-with-icon">Ajaloolised kaardid</span>
  </a>
  <a
          href="{% url 'blog:blog_index' %}"
          class="w3-bar-item w3-button">
    <i class="{% icon_artikkel %}s-o"></i>
    <span class="bar-item-text-with-icon">Blogi</span>
  </a>
  <a
          href="{% url 'ilm:index' %}"
          class="w3-bar-item w3-button">
    <i class="fa fa-thermometer"></i>
    <span class="bar-item-text-with-icon">Valga linna ilm</span>
  </a>
  <a
          href="https://et.wikipedia.org/wiki/Valga_(Liivimaa)"
          target="blank"
          class="w3-bar-item w3-button">
    <i class="fa fa-wikipedia-w"></i>
    <span class="bar-item-text-with-icon">Valga Vikipeedias</span>
  </a>
  <a
          href="https://www.facebook.com/valgalinn/"
          target="blank"
          class="w3-bar-item w3-button">
    <i class="fa fa-facebook-official"></i>
    <span class="bar-item-text-with-icon">Valga Facebook</span>
  </a>
  <a
          href="https://www.instagram.com/valgalinn/"
          target="blank"
          class="w3-bar-item w3-button">
    <i class="fa fa-instagram"></i>
    <span class="bar-item-text-with-icon">Valga Instagram</span>
  </a>
  <a
          href="{% url 'info' %}"
          class="w3-bar-item w3-button"
          title="Projektist"><i class="fa fa-info"></i>
    <span class="bar-item-text-with-icon">Projektist</span>
  </a>
</div>

wiki/templates/wiki/wiki_base/wiki_base_ogp.html
{#object = detailview 'object'#}
{% load static %}
{% load wiki_extras %}
<meta property="og:locale" content="et_EE" />
<meta property="og:site_name" content="Valga linna kroonika" />
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:title" content="Valga linna kroonika{% if object %} - {{ object }}{% endif%}" />
{% if object %}
  <meta property="og:type" content="article" />
  <meta property="og:description" content="{{ object }}" />
  <meta property="article:section" content="{% get_verbose_name_plural object %}" />
  <meta property="article:published_time" content="{{ object.mod_date|date:'c' }}" />
  <meta property="article:modified_time" content="{{ object.mod_date|date:'c' }}" />
  <meta property="og:updated_time" content="{{ object.mod_date|date:'c' }}" />
{% else %}
  <meta property="og:type" content="website" />
  <meta property="og:description" content="{% description %}" />
{% endif %}
{% comment %} FB share jaoks {% endcomment %}
<meta property="fb:app_id" content="275987973680424" />