ilm/urls.py
from django.urls import path, include
from . import views

app_name = 'ilm'
urlpatterns = [
    path('', views.index, name='index'),
    # path('mobile/', views.index_mobile, name='index_mobile'),
    path('history/', views.history, name='history'),
    path('forecasts/', views.forecasts, name='forecasts'),
    path('forecasts/<str:asukoht>/', views.forecasts, name='forecasts_with_asukoht'),
    # path('forecasts_yrno/', views.forecasts_yrno, name='forecasts_yrno'),
    path('forecasts_quality/', views.forecasts_quality, name='forecasts_quality'),
    path('maxmin/', views.maxmin, name='maxmin'),
    path('mixed_ilmateade/', views.mixed_ilmateade, name='mixed_ilmateade'),
    path('container_history_andmed/', views.container_history_andmed, name='container_history_andmed'),
    path('container_history_aasta/', views.container_history_aasta, name='container_history_aasta'),
    path('container_history_kuud/', views.container_history_kuud, name='container_history_kuud'),
    path('container_history_kuu/', views.container_history_kuu, name='container_history_kuu'),
    path('container_history_kuud_aastatekaupa/', views.container_history_kuud_aastatekaupa, name='container_history_kuud_aastatekaupa'),
    path('container_history_p2ev/', views.container_history_p2ev, name='container_history_p2ev'),
    path('container_history_p2evad/', views.container_history_p2evad, name='container_history_p2evad'),
    path('container_history_aastad/', views.container_history_aastad, name='container_history_aastad'),
    # path('pyimage/', PyImageView.as_view(), name='pyimage_view'),
]

kiri/urls.py
from django.urls import path
from .views import KiriView, KiriSuccessView

app_name = 'kiri'

urlpatterns = [
    path('', KiriView.as_view(), name="index"),
    path('success/<str:email_to>|<str:subject>', KiriSuccessView.as_view(), name="success"),
]

kroonika/urls.py
# kroonika URL Configuration

from ajax_select import urls as ajax_select_urls

# from django.contrib.auth import views as auth_views
from django.conf import settings
# from django.conf.urls import handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

from .sitemaps import StaticViewSitemap, ArtikkelSitemap, IsikSitemap, OrganisatsioonSitemap, ObjektSitemap
from .routers import router
from wiki import views, specials

# sitemaps.xml
sitemaps = {
    'static': StaticViewSitemap,
    'lood': ArtikkelSitemap,
    'isikud': IsikSitemap,
    'asutised': OrganisatsioonSitemap,
    'kohad': ObjektSitemap
}

# schema_url_patterns = [
#     path('api/', include(router.urls)),
# ]

# API
schema_view = get_schema_view(
    title='Valga linna kroonika API',
    # url='https://valgalinn/api/',
    # patterns=schema_url_patterns
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.algus, name='algus'),
    path('info/', views.info, name='info'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')), # django-allauth
    path('ajax_select/', include(ajax_select_urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	path('api/', include(router.urls)),
    path('blog/', include('blog.urls'), name='blog'),
    path('kiri/', include('kiri.urls'), name='kiri'),
    path('ilm/', include('ilm.urls'), name='ilm'),
    path('inlineedit/', include('inlineedit.urls'), name='save'), # https://github.com/ptav/django-inlineedit
    path('docs/', include_docs_urls(title='Valga linna kroonika API')),
    path('markdownx/', include('markdownx.urls')),
    path('privacy/', views.privacy, name='privacy'),
    path('schema/', schema_view),
    path('wiki/', include('wiki.urls')),
    path('kaart/', views.kaart, name='kaart'),
    path('kaart/get_big_leaflet_map/', views.get_big_leaflet_map, name='get_big_leaflet_map'),
    path('kaart/<int:aasta>/', views.kaart, name='kaart'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('valga438/', specials.special_valga438, name='special_valga438'),
    # path('valga439/', specials.special_valga439, name='special_valga439'),
    # path('valga440/', specials.special_valga440, name='special_valga440'),
    # path('valga441/', specials.special_valga441, name='special_valga441'),
    # path('j6ul2020/', specials.special_j6ul2020, name='special_j6ul2020'),
    # path('j6ul2021/', specials.special_j6ul2021, name='special_j6ul2021'),
    # path('j6ul2022/', specials.special_j6ul2022, name='special_j6ul2022'),
    # path('j6ul2023/', specials.special_j6ul2023, name='special_j6ul2023'),
    # path('j6ul2024/', specials.special_j6ul2024, name='special_j6ul2024'),
    path('j6ul2025/', specials.special_j6ul2025, name='special_j6ul2025'),
    path('vgvk/', include('vgvk.urls')),
    path('raise_500_error/', views.raise_500_error, name='raise_500_error'), # http500 veateate testimiseks
    # path("__debug__/", include("debug_toolbar.urls")), # https://django-debug-toolbar.readthedocs.io
]

#error handling
handler500 = 'wiki.views.custom_500'

# Haldusliidese pealkirjad
admin.site.site_header = 'valgalinn.ee sisuhaldus'
admin.site.site_title = 'valgalinn.ee sisuhaldus'

# Serve static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve user uploaded media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kiri/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

class KiriForm(forms.Form):

    name = forms.CharField(
        max_length=120,
        initial='valgalinn.ee',
        required=False,
        label='Saatja nimi'
    )
    email_from = forms.EmailField(
        initial=settings.DEFAULT_FROM_EMAIL,
        label='Saatja aadress'
    )
    email_to = forms.EmailField(
        label='Saaja aadress'
    )

    subject = forms.CharField(
        max_length=70,
        label='Pealkiri'
    )
    message = forms.CharField(
        widget=forms.Textarea,
        label='Kirja sisu'
    )
    file_field = forms.FileField(
        # widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input my-3', 'multiple': True}),
        # required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input my-3', "allow_multiple_selected": True}), required=False,
        label=''
    )

    def get_info(self):
        """
        Method that returns formatted information
        :return: name, email_from, email_to, subject, message
        """
        # Cleaned data
        cl_data = super().clean()

        name = cl_data.get('name').strip()
        email_from = cl_data.get('email_from')
        email_to = cl_data.get('email_to')
        subject = cl_data.get('subject')
        message = cl_data.get('message')

        return name, email_from, email_to, subject, message

    def send(self, files):
        name, email_from, email_to, subject, message = self.get_info()
        if name:
            email_from = f'{name} <{email_from}>'

        # send_mail(
        #     subject=subject,
        #     message=msg,
        #     from_email=email_from, # f'{name} <{email_from}>'
        #     recipient_list=[email_to]
        # )

        merge_data = {
            'name': name,
            'subject': subject,
            'message': message,
            'email_from': email_from
        }
        html_content = render_to_string('kiri/email_base.html', merge_data)
        msg = EmailMultiAlternatives(
            subject,
            message,
            email_from,
            [email_to]
        )
        msg.attach_alternative(html_content, "text/html")

        import mimetypes
        if files: # kui failid lisatud
            for f in files:
                print(dir(f))
                print(f.name, f.file, f.content_type)
                msg.attach(f.name, f.read(), f.content_type)
                # filename, content and mimetype

        msg.send(fail_silently=False)

        return email_to, subject

kiri/views.py
from email.mime.image import MIMEImage
import os

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from .forms import KiriForm

class KiriView(LoginRequiredMixin, FormView):
    redirect_field_name = 'next'
    template_name = 'kiri/contact.html'
    form_class = KiriForm
    success_url = reverse_lazy('kiri:success', kwargs={'email_to': '', 'subject': ''})

    # def form_valid(self, form):
    #     # Calls the custom send method
    #     email_to, subject = form.send()
    #     self.success_url = reverse_lazy('kiri:success', kwargs={'email_to': email_to, 'subject': subject})
    #     return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('file_field')
            email_to, subject = form.send(files)
            self.success_url = reverse_lazy('kiri:success', kwargs={'email_to': email_to, 'subject': subject})
            return super().form_valid(form)
        else:
            return render(request, self.template_name, {'form': form})

class KiriSuccessView(TemplateView):
    template_name = 'kiri/success.html'

    def get(self, request, email_to=None, subject=None, *args, **kwargs):
        context = {
            'email_to': email_to,
            'subject': subject
        }
        return render(request, self.template_name, context)


# e-postiga j6ukukaarti saatmiseks
def send_j6ulukaart():

    saajad = [
        'valga@valga.ee',
        'muuseum@valgamuuseum.ee',
        'valgamaa@redcross.ee',
        'valga@isamaalinemuuseum.ee',
        'ivar.mottus@gmail.com',
        'priit@valgamuuseum.ee',
        'margussuvi@gmail.com',
        'jaanrapp@hot.ee',
        'ellenmuru41@gmail.com',
        'aasa.poder@gmail.com',
        'rainerkuutma@hotmail.com',
        'kool@valgagym.ee'
    ]

    name = 'valgalinn.ee',
    email_from = 'valgalinn.ee <info@valgalinn.ee>'
    email_to = ['info@valgalinn.ee']
    bcc = saajad # ['kalev.hark@mail.ee', 'kalevhark@gmail.com', 'kalev.hark@sotsiaalkindlustusamet.ee']
    subject = 'valgalinn.ee jõulutervitus'
    message  = ''

    merge_data = {
        'name': name,
        'subject': subject,
        'message': message,
        'email_from': email_from,
        'valgalinn_ee_logo': 'valgalinn_ee_logo.png',
        'valgalinn_ee_j6ulukaart': 'valgalinn_ee_j6ulukaart2023.jpg',
        'valgalinn_ee_j6ulukaart_imagefile': 'VaMFp4053F2891-334_1_j6ul2023_kaart.jpg',
    }

    html_content = render_to_string('kiri/email_j6ulukaart2023.html', merge_data)
    msg = EmailMultiAlternatives(
        subject,
        message,
        email_from,
        email_to,
        bcc,
    )
    msg.attach_alternative(html_content, "text/html")
    msg.content_subtype = 'html'
    msg.mixed_subtype = 'related'

    print(settings.BASE_DIR)

    # lisame logo:
    img_path = os.path.join(settings.BASE_DIR, 'wiki/static/wiki/favicon-32x32.png')
    with open(img_path, 'rb') as f:
        banner_image = MIMEImage(f.read())
        banner_image.add_header('Content-ID', f'<{merge_data["valgalinn_ee_logo"]}>')
        msg.attach(banner_image)

    # lisame j6ulukaardi:
    img_path = os.path.join(settings.BASE_DIR, f'wiki/static/wiki/img/special/{merge_data["valgalinn_ee_j6ulukaart_imagefile"]}')
    with open(img_path, 'rb') as f:
        banner_image = MIMEImage(f.read())
        banner_image.add_header('Content-ID', f'<{merge_data["valgalinn_ee_j6ulukaart"]}>')
        msg.attach(banner_image)

    # import mimetypes
    # if files: # kui failid lisatud
    #     for f in files:
    #         print(dir(f))
    #         print(f.name, f.file, f.content_type)
    #         msg.attach(f.name, f.read(), f.content_type)
    #         # filename, content and mimetype

    msg.send(fail_silently=False)

kiri/templates/kiri/contact.html
{% extends 'kiri/kiri_base.html' %}
{% load crispy_forms_tags %}

{% block stylesheet %}
  <style>
    .custom-file-input::-webkit-file-upload-button {
      visibility: hidden;
    }
    .custom-file-input::before {
      content: 'Lisatud failid';
      display: inline-block;
      background: -webkit-linear-gradient(top, #f9f9f9, #e3e3e3);
      border: 1px solid #999;
      border-radius: 3px;
      padding: 5px 8px;
      outline: none;
      white-space: nowrap;
      -webkit-user-select: none;
      cursor: pointer;
      text-shadow: 1px 1px #fff;
      font-weight: 700;
      font-size: 10pt;
    }
    .custom-file-input:hover::before {
      border-color: black;
    }
    .custom-file-input:active::before {
      background: -webkit-linear-gradient(top, #e3e3e3, #f9f9f9);
    }
  </style>
{% endblock %}

{% block content %}
<div class="mx-auto my-4 text-center">
    <h1>valgalinn.ee kirjasaatja</h1>
</div>
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
    <button class="btn btn-success" type="submit">Saada kiri</button>
    </form>
</div>
{% endblock %}

{% block javascript %}
  <script>
    $(document).on('change', '.custom-file-input', function (event) {
        console.log(event.target.files);
    })
  </script>
{% endblock %}

kiri/templates/kiri/email_base.html
<!doctype html>
{% load static %}
<html lang="et">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Simple Transactional Email</title>
    <style>
      /* -------------------------------------
          GLOBAL RESETS
      ------------------------------------- */

      /*All the styling goes here*/

      img {
        border: none;
        -ms-interpolation-mode: bicubic;
        max-width: 100%;
      }

      body {
        background-color: #f6f6f6;
        font-family: sans-serif;
        -webkit-font-smoothing: antialiased;
        font-size: 14px;
        line-height: 1.4;
        margin: 0;
        padding: 0;
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%;
      }

      table {
        border-collapse: separate;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
        width: 100%; }
        table td {
          font-family: sans-serif;
          font-size: 14px;
          vertical-align: top;
      }

      /* -------------------------------------
          BODY & CONTAINER
      ------------------------------------- */

      .body {
        background-color: #f6f6f6;
        width: 100%;
      }

      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
        display: block;
        margin: 0 auto !important;
        /* makes it centered */
        max-width: 580px;
        padding: 10px;
        width: 580px;
      }

      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
        box-sizing: border-box;
        display: block;
        margin: 0 auto;
        max-width: 580px;
        padding: 10px;
      }

      /* -------------------------------------
          HEADER, FOOTER, MAIN
      ------------------------------------- */
      .main {
        background: #ffffff;
        border-radius: 3px;
        width: 100%;
      }

      .wrapper {
        box-sizing: border-box;
        padding: 20px;
      }

      .content-block {
        padding-bottom: 10px;
        padding-top: 10px;
      }

      .header {
        clear: both;
        margin-top: 10px;
        text-align: center;
        width: 100%;
      }
        .header td,
        .header p,
        .header span,
        .header a {
          color: #00985F;
          font-size: 1em;
          text-align: center;
      }

      .footer {
        clear: both;
        margin-top: 10px;
        text-align: center;
        width: 100%;
      }
        .footer td,
        .footer p,
        .footer span,
        .footer a {
          color: #999999;
          font-size: 12px;
          text-align: center;
      }

      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1,
      h2,
      h3,
      h4 {
        color: #000000;
        font-family: sans-serif;
        font-weight: 400;
        line-height: 1.4;
        margin: 0;
        margin-bottom: 30px;
      }

      h1 {
        font-size: 35px;
        font-weight: 300;
        text-align: center;
        text-transform: capitalize;
      }

      p,
      ul,
      ol {
        font-family: sans-serif;
        font-size: 14px;
        font-weight: normal;
        margin: 0;
        margin-bottom: 15px;
      }
        p li,
        ul li,
        ol li {
          list-style-position: inside;
          margin-left: 5px;
      }

      a {
        color: #3498db;
        text-decoration: underline;
      }

      /* -------------------------------------
          BUTTONS
      ------------------------------------- */
      .btn {
        box-sizing: border-box;
        width: 100%; }
        .btn > tbody > tr > td {
          padding-bottom: 15px; }
        .btn table {
          width: auto;
      }
        .btn table td {
          background-color: #ffffff;
          border-radius: 5px;
          text-align: center;
      }
        .btn a {
          background-color: #ffffff;
          border: solid 1px #3498db;
          border-radius: 5px;
          box-sizing: border-box;
          color: #3498db;
          cursor: pointer;
          display: inline-block;
          font-size: 14px;
          font-weight: bold;
          margin: 0;
          padding: 12px 25px;
          text-decoration: none;
          text-transform: capitalize;
      }

      .btn-primary table td {
        background-color: #3498db;
      }

      .btn-primary a {
        background-color: #3498db;
        border-color: #3498db;
        color: #ffffff;
      }

      /* -------------------------------------
          OTHER STYLES THAT MIGHT BE USEFUL
      ------------------------------------- */
      .last {
        margin-bottom: 0;
      }

      .first {
        margin-top: 0;
      }

      .align-center {
        text-align: center;
      }

      .align-right {
        text-align: right;
      }

      .align-left {
        text-align: left;
      }

      .clear {
        clear: both;
      }

      .mt0 {
        margin-top: 0;
      }

      .mb0 {
        margin-bottom: 0;
      }

      .preheader {
        color: transparent;
        display: none;
        height: 0;
        max-height: 0;
        max-width: 0;
        opacity: 0;
        overflow: hidden;
        mso-hide: all;
        visibility: hidden;
        width: 0;
      }

      .powered-by a {
        text-decoration: none;
      }

      hr {
        border: 0;
        border-bottom: 1px solid #f6f6f6;
        margin: 20px 0;
      }

      /* -------------------------------------
          RESPONSIVE AND MOBILE FRIENDLY STYLES
      ------------------------------------- */
      @media only screen and (max-width: 620px) {
        table.body h1 {
          font-size: 28px !important;
          margin-bottom: 10px !important;
        }
        table.body p,
        table.body ul,
        table.body ol,
        table.body td,
        table.body span,
        table.body a {
          font-size: 16px !important;
        }
        table.body .wrapper,
        table.body .article {
          padding: 10px !important;
        }
        table.body .content {
          padding: 0 !important;
        }
        table.body .container {
          padding: 0 !important;
          width: 100% !important;
        }
        table.body .main {
          border-left-width: 0 !important;
          border-radius: 0 !important;
          border-right-width: 0 !important;
        }
        table.body .btn table {
          width: 100% !important;
        }
        table.body .btn a {
          width: 100% !important;
        }
        table.body .img-responsive {
          height: auto !important;
          max-width: 100% !important;
          width: auto !important;
        }
      }

      /* -------------------------------------
          PRESERVE THESE STYLES IN THE HEAD
      ------------------------------------- */
      @media all {
        .ExternalClass {
          width: 100%;
        }
        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
          line-height: 100%;
        }
        .apple-link a {
          color: inherit !important;
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          text-decoration: none !important;
        }
        #MessageViewBody a {
          color: inherit;
          text-decoration: none;
          font-size: inherit;
          font-family: inherit;
          font-weight: inherit;
          line-height: inherit;
        }
        .btn-primary table td:hover {
          background-color: #34495e !important;
        }
        .btn-primary a:hover {
          background-color: #34495e !important;
          border-color: #34495e !important;
        }
      }

    </style>
  </head>
  <body class="">
    <span class="preheader">Tagaside: </span>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <td>&nbsp;</td>
        <td class="container">
          <div class="content">

            <!-- START HEADER -->
            <div class="header">
              <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block powered-by">
                    <a
                          href="https://valgalinn.ee">
                            <img
                              src="https://valgalinn.ee{% static 'wiki/favicon-32x32.png' %}"
                              alt="valgalinn.ee logo"/><br>valgalinn.ee
                    </a>
                  </td>
                </tr>
              </table>
            </div>
            <!-- END HEADER -->

            <!-- START CENTERED WHITE CONTAINER -->
            <table role="presentation" class="main">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper">
                  <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td>
                        <p>{{ message | linebreaks }}</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <p></p>
                        <p>{{ email_from }}</p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>
            <!-- END CENTERED WHITE CONTAINER -->

            <!-- START FOOTER -->
            <div class="footer">
              <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block powered-by">
                    Saadetud veebilehelt <a href="https://valgalinn.ee">valgalinn.ee</a>.
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->

          </div>
        </td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

kiri/templates/kiri/kiri_base.html
<!DOCTYPE html>
<html lang="et">
	<meta charset="utf-8">
	<head>
		<title>{% block title %}Valga linna kroonika kirjasaatja{% endblock %}</title>
		{% load static %}
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta name="description"          content="Valga linna kroonika kirjasaatja" />
		<meta name="keywords"             content="Valga, linn, kroonika, ajalugu, blog" />
		<meta name="author"               content="Kalev Härk" />
		<meta name="viewport"             content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<!-- Kirjeldus -->
		<meta property="og:type"          content="website" />
		<meta property="og:title"         content="Valga linna kroonika kirjasaatja" />
		<meta property="og:description"   content="Valga linna kroonika kirjasaatja" />
		<meta property="og:image"         content="{% static 'wiki/img/android-chrome-512x512.png' %}" />
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
            crossorigin="anonymous" /
    >
		<!-- Custom CSS -->
		<link rel="stylesheet" href="{% static 'wiki/css/kroonika_general.css' %}">
  	<!--  Alternatiivsed värvivalikud metro või colorful-->
  	<link rel="stylesheet" href="{% static 'wiki/css/kroonika_color_metro.css' %}">
		{% block stylesheet %}{% endblock %}
		<link rel="shortcut icon" href="{% static 'wiki/favicon.ico' %}">
  </head>
  <body class="Site w3-light-grey">
    <header>
			<!-- Navbar -->
			<div id="top" class="w3-top">
				<div class="w3-bar w3-left-align w3-large">
					<a
						href="{% url 'algus' %}"
						title="Valga linna kroonika avalehele"
						class="w3-bar-item w3-button w3-hover-white">
						<img
								src="{% static 'wiki/favicon-32x32.png' %}"
								style='max-height:22px;'
								alt="vapp">
					</a>
					<a
							href="{% url 'kiri:index' %}"
							class="w3-bar-item w3-button w3-theme-d4 w3-hover-white">
						<i
								id="kiri_start_icon"
								style="display: inline-block; margin-right: 10px;"
								class="fa fa-envelope">
						</i>
						valgalinn.ee kirjasaatja
					</a>
					<a
							href="{% url 'algus' %}"
							class="w3-bar-item w3-button w3-hover-white w3-hide-small"
							title="Valga linna kroonika">
						<i class="fa fa-leanpub"></i>
					</a>
          <a
              href="{% url 'info' %}"
              class="w3-bar-item w3-button w3-hover-white w3-hide-small"
              title="Projektist">
            <i class="fa fa-info"></i>
          </a>

          <!-- Kasutaja ja adminlingid -->
          {% if user.is_authenticated %}
            <a
                href="{% url 'account_logout' %}?next={{ request.path | urlencode }}"
                class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-text-grey w3-hover-white w3-right"
                title="Logi välja">{{ user.first_name }}&nbsp;<i class="fa fa-sign-out"></i>
            </a>
          {% else %}
            <a
                href="{% url 'account_login' %}?next={{ request.path }}"
                class="w3-bar-item w3-button w3-hide-medium w3-hide-small w3-text-grey w3-hover-white w3-right"
                title="Logi sisse">
              <i class="fa fa-sign-in"></i>
            </a>
          {% endif %}
				</div>
			</div>
		</header>

		<main>
      {% block content %}{% endblock %}
    </main>

    <footer>
	  <div class="w3-bar">
      <a href="#">
	      <button class="w3-button w3-hover-white fa fa-angle-double-up"></button>
	    </a>
	    <a href="{% url 'info' %}">
          <button class="w3-button w3-hover-white w3-right w3-text-grey"><small>&#9400;&nbsp;2018-{% now "Y" %} Kalev Härk</small></button>
	    </a>
      </div>
		</footer>

    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
            crossorigin="anonymous"
    ></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

		<!-- Äpi skriptid, kui vaja -->
	  {% block javascript %}{% endblock %}
	</body>
</html>

kiri/templates/kiri/success.html
{% extends 'kiri/kiri_base.html' %}

{% block content %}
<div class="mx-auto my-4 text-center">
  <h1 class="fw-bolder text-success">Kiri <strong>{{ subject }}</strong><br>saadetud <strong>{{ email_to }}</strong>.</h1>
  <p class="my-5">Saada uus kiri <a href="{% url 'kiri:index' %}">valgalinn.ee kirjasaatjast</a></p>
</div>
{% endblock %}